In [1]:
import pandas as pd

In [3]:
All = pd.read_csv("NFL_Punt/All_Injuries.csv")

In [4]:
All.head()

,PlayKey,Position,Injury,x,y,o,dir,Twist
0,252-231-30982,CB,Concussion,46.209999,45.23,147.750000,315.339996,167.589996
1,252-231-30982,CB,Concussion,46.209999,45.23,147.750000,315.339996,167.589996
2,252-231-30982,CB,Concussion,46.209999,45.23,147.750000,315.339996,167.589996
3,252-231-32070,WR,Concussion,46.259998,24.85,206.080002,264.890015,58.810013
4,252-231-30084,SS,Concussion,45.740002,7.09,153.160004,69.709999,83.450005

In [5]:
df_unique = All.drop_duplicates(subset=['PlayKey'])

In [6]:
df_unique.head()

,PlayKey,Position,Injury,x,y,o,dir,Twist
0,252-231-30982,CB,Concussion,46.209999,45.230000,147.750000,315.339996,167.589996
3,252-231-32070,WR,Concussion,46.259998,24.850000,206.080002,264.890015,58.810013
4,252-231-30084,SS,Concussion,45.740002,7.090000,153.160004,69.709999,83.450005
5,252-231-26672,OLB,Concussion,46.160000,27.280001,222.669998,28.139999,194.529999
7,252-231-29658,CB,Concussion,45.919998,43.299999,185.440002,311.010010,125.570007

In [7]:
df_unique.to_csv("NFL_Punt/All_Injuries_End.csv", index=False)